.aliases:
  - &shared
    only:
      - f/anu-gitlab-ci
    cache:
      key: ${CI_COMMIT_REF_SLUG}
      paths:
        # common
        - $HOME/.local
        - $HOME/.npm
        # darwin
        - $HOME/.homebrew
        - $HOME/Library/Caches/Homebrew
        - $HOME/Library/Caches/pip
        # linux
        - $HOME/.cache/Homebrew
        - $HOME/.cache/pip
        - $HOME/.linuxbrew


stages:
  - test


install_job:
  <<: *shared
  stage: test
  before_script:
    - ./.ci.sh before_install
  script:
    - ./.ci.sh install

script_job:
  <<: *shared
  dependencies:
    - install_job
  stage: test
  before_script:
    - ./.ci.sh before_script
  script:
    - ./.ci.sh script

cache_job:
  <<: *shared
  dependencies:
    - script_job
  stage: test
  before_script:
    - ./.ci.sh before_cache
  script:
    - 'true'
  allow_failure: true
  when: on_success

after_success_job:
  <<: *shared
  dependencies:
    - cache_job
  stage: test
  script:
    - ./.ci.sh after_success
  allow_failure: true
  when: on_success

after_failure_job:
  <<: *shared
  dependencies:
    - script_job
  stage: test
  script:
    - ./.ci.sh after_failure
  allow_failure: true
  when: on_failure

deploy_job:
  <<: *shared
  dependencies:
    - after_success_job
  stage: test
  before_script:
    - ./.ci.sh before_deploy
  script:
    - ./.ci.sh deploy
  after_script:
    - ./.ci.sh after_deploy
  when: on_success
  only:
    - tags

after_script_job:
  <<: *shared
  dependencies:
    - after_success_job
    - after_failure_job
  stage: test
  script:
    - ./.ci.sh after_script
  allow_failure: true
  when: always
