.aliases:
  - &shared
    image: ubuntu:16.04
    only:
      - f/anu-gitlab-ci
    cache:
      key: ${CI_COMMIT_REF_SLUG}
      paths:
        # common
        - $HOME/.local
        - $HOME/.npm
        # darwin
        - $HOME/.homebrew
        - $HOME/Library/Caches/Homebrew
        - $HOME/Library/Caches/pip
        # linux
        - $HOME/.cache/Homebrew
        - $HOME/.cache/pip
        - $HOME/.linuxbrew


stages:
  - test_install
  - test_script
  - test_cache
  - test_after_success
  - test_after_failure
  - test_deploy
  - test_after_script


install_job:
  <<: *shared
  stage: test_install
  before_script:
    - ./.ci.sh before_install
  script:
    - ./.ci.sh install

script_job:
  <<: *shared
  dependencies:
    - install_job
  stage: test_script
  before_script:
    - ./.ci.sh before_script
  script:
    - ./.ci.sh script

cache_job:
  <<: *shared
  dependencies:
    - script_job
  stage: test_cache
  before_script:
    - ./.ci.sh before_cache
  script:
    - 'true'
  allow_failure: true
  when: on_success

after_success_job:
  <<: *shared
  dependencies:
    - cache_job
  stage: test_after_success
  script:
    - ./.ci.sh after_success
  allow_failure: true
  when: on_success

after_failure_job:
  <<: *shared
  dependencies:
    - script_job
  stage: test_after_failure
  script:
    - ./.ci.sh after_failure
  allow_failure: true
  when: on_failure

deploy_job:
  <<: *shared
  dependencies:
    - after_success_job
  stage: test_deploy
  before_script:
    - ./.ci.sh before_deploy
  script:
    - ./.ci.sh deploy
  after_script:
    - ./.ci.sh after_deploy
  when: on_success
  only:
    - tags

after_script_job:
  <<: *shared
  dependencies:
    - after_success_job
    - after_failure_job
  stage: test_after_script
  script:
    - ./.ci.sh after_script
  allow_failure: true
  when: always
