# 0. Misc
# matrix:

# 1. Notifications
notifications:
  slack:
    rooms:
      - secure: ""
    on_success: change
    on_pull_requests: false

# 2. Env
env:
  global:
    - ""

# 3. Git
git:
  submodules: false
branches:
  except:
    - /^f\// # feature branches require PR

# 4. Bootstrap
# os: linux
# dist: trusty
# sudo: false
language:
  - node_js
node_js:
  - node
# addons:
before_cache: ./.travis.sh before_cache
cache:
  directories:
    # common
    - $HOME/.local
    - $HOME/.npm
    # darwin
    - $HOME/Library/Caches/Homebrew
    - $HOME/Library/Caches/pip
    # linux
    - $HOME/.cache/Homebrew
    - $HOME/.cache/pip
    - $HOME/.linuxbrew

# 5. Steps
before_install: ./.travis.sh before_install
install: ./.travis.sh install
before_script: ./.travis.sh before_script
script: ./.travis.sh script
after_success: ./.travis.sh after_success
after_failure: ./.travis.sh after_failure
after_script: ./.travis.sh after_script

# 6. Deploy
before_deploy: ./.travis.sh before_deploy
# deploy:
after_deploy: ./.travis.sh after_deploy
